server:
  port: 9001
spring:  application:    name: zuul
eureka:  client:    service-url:      defaultZone: http://localhost:9000/eureka/
zuul:  routes:    user:
      service-id: user-provider
      path: /user/**
    goods:
      service-id: goods-provider
      path: /goods/**    orders:
      service-id: orders-provider
      path: /orders/** 